### ISSUE TITLE
[BUG] Installing plugin makes "item help" window constantly pushed upwards to the top of the screen

### ISSUE THREAD

**Issue by liamont** [Kouzukii/ffxiv-priceinsight#18]
Usually I set my "item help" window in the bottom left corner, like so: 
![screenshot](https://i.imgur.com/8B52sl4.png)
However, after installing the priceinsight plugin, the "item help" window is constantly pushed to the top of the screen the second I mouseover an item. The height that it is pushed up appears to be linked to how high the window needs to go for the price insights to show up. This causes the user to need to constantly open up the HUD Layout to change the "item help" window back into its original position.

A fix would be greatly appreciated, as the plugin itself is extremely useful.

**Comment by Yueh72** [comment]
I got the same bug

**Comment by arorer** [comment]
This same issue is still occurring. I am not sure why but it is still moving any the only fix (for a short time) is to re open and close (twice) the Hub layout. They it resets back at the bottom to be slowly lifted again. This bug is super breaking for me as it slowly takes over my right side of the screen.

**Comment by Kouzukii** [comment]
Should be fixed in the latest update
