### ISSUE TITLE
Tooltip overflows offscreen when using fixed tooltip position

### ISSUE THREAD

**Issue by mustafakalash** [Kouzukii/ffxiv-priceinsight#36]
If a tooltip is too tall to fit on screen when using the fixed tooltip position option, it normally will offset to stay on screen:
![image](https://github.com/Kouzukii/ffxiv-priceinsight/assets/313146/0622f28b-e0bd-44fa-b799-83ed3c07d265)
Other plugins that add entries to the tooltip, such as AllaganTools, maintain this functionality. However, PriceInsight's entries will cause an overflow:
![image](https://github.com/Kouzukii/ffxiv-priceinsight/assets/313146/d9b79bf6-6bda-4ed2-9362-6286c114130f)
The price and the bottom of the tooltip are offscreen and not visible.

**Comment by eigoor** [comment]
I have the same issue. From what I can see the problem seems to be that the tooltip is calculated based on a 100% UI scale. I'm using 150% UI scale and am seeing the same issue.

If I modify the following line to multiply the itemTooltipheight by 1.5 then the calculaion works correctly.
https://github.com/Kouzukii/ffxiv-priceinsight/blob/b54bae279fee1ba2824a5709f66848ffb53d4148/ItemPriceTooltip.cs#L95

Unfortunately I was not able to find a way to get the scaling factor from dalamud.
